### ISSUE TITLE
How is it different from https://github.com/dedupeio/dedupe

### ISSUE THREAD

**Issue by abhilashchowdhary** [fritshermans/deduplipy#14]
I currently use https://github.com/dedupeio/dedupe and was curious if you there are any specific pain points which this library solves over it? From my cursory look, is one of the major differences the use of modAL library rather than custom built active learning solution in dedupe?

(Apologies if I'm abusing the power of opening an issue to ask this question)

**Comment by fritshermans** [comment]
The main difference is that DedupliPy offers more advanced settings like custom blocking rules and thresholding on the probability scores. These are not just small nice-to-haves but they make the difference between being able to run the algorithm on large data or not. Moreover, in DedupliPy pair sampling is done using min hashing (resulting in a wide variety of probability scores that the active learner can pick from) and missing probabilities in the adjacency matrix are filled using the SoftImpute algorithm instead of zeros.

No problem for opening an issue 🙂
